export const REPRESENTATIVE_PHONE_DISPLAY = "+55 49 2020-9980";
export const REPRESENTATIVE_PHONE_DIGITS = "554920209980";
export const REPRESENTATIVE_PHONE_TEL = `tel:+${REPRESENTATIVE_PHONE_DIGITS}`;
export const REPRESENTATIVE_PHONE_WHATSAPP = `https://wa.me/${REPRESENTATIVE_PHONE_DIGITS}`;

const WHATSAPP_MESSAGE = encodeURIComponent("Olá! Preciso de ajuda com o catálogo Clinic+.");

export const REPRESENTATIVE_PHONE_WHATSAPP_URL = `${REPRESENTATIVE_PHONE_WHATSAPP}?text=${WHATSAPP_MESSAGE}`;

