-- Generated from catalogo_clinic+ (4).pdf on 2026-04-03
insert into public."Clinic+ - Catálogo Front B2B" (name, description, type, family) values
  ('Whey Mais Ella Isolado + Colágeno sabor Neutro', 'Cod. 5840 - Lata c/400 g', 'Solúvel', 'Whey Mais Ella'),
  ('Whey Mais Ella Isolado + Colágeno sabor Banana Flambada', 'Cod. 6273 - Lata c/400 g', 'Solúvel', 'Whey Mais Ella'),
  ('Whey Mais Ella Isolado + Colágeno sabor Mousse de Limão', 'Cod. 7513 - Lata c/400 g', 'Solúvel', 'Whey Mais Ella'),
  ('Whey Mais Pleno Isolado sabor Baunilha', 'Cod. 5844 - Lata c/ 300 g', 'Solúvel', 'Whey Mais Pleno'),
  ('Whey Mais ISO sabor Neutro', 'Cod. 7178 - Pote c/900 g', 'Solúvel', 'Whey Mais ISO'),
  ('Whey Mais ISO sabor Neutro', 'Cod. 7179 - Lata c/400 g', 'Solúvel', 'Whey Mais ISO'),
  ('Whey Mais 100% Concentrate sabor Morango', 'Cod. 6947 - Pote c/900 g', 'Solúvel', 'Whey Mais 100%'),
  ('Whey Mais 100% Concentrate sabor Chocolate Belga', 'Cod. 6946 - Pote c/900 g', 'Solúvel', 'Whey Mais 100%'),
  ('Whey Mais 100% Concentrate sabor Baunilha e Banana Caramelizada', 'Cod. 6945 - Pote c/900 g', 'Solúvel', 'Whey Mais 100%'),
  ('Whey Mais Concentrado sabor Chocolate', 'Cod. 6981 - Pote c/900 g', 'Solúvel', 'Whey Mais Concentrado'),
  ('Whey Mais Concentrado sabor Morango', 'Cod. 6980 - Pote c/900 g', 'Solúvel', 'Whey Mais Concentrado'),
  ('Whey Mais Concentrado sabor Baunilha e Quatro Leites', 'Cod. 6979 - Pote c/900 g', 'Solúvel', 'Whey Mais Concentrado'),
  ('Protein Mais Colágeno Hidrolisado BODYBALANCE® sabor Neutro', 'Cod. 7431 - Lata c/450 g', 'Solúvel', 'Protein Mais Colágeno'),
  ('Peptgenderma9 Colágeno Premium sabor Laranja com Gengibre', 'Cod. 4461 - Lata c/300 g', 'Solúvel', 'Peptgenderma9 Colágeno'),
  ('Peptgenderma9 Colágeno Premium sabor Limão Siciliano', 'Cod. 4463 - Lata c/300 g', 'Solúvel', 'Peptgenderma9 Colágeno'),
  ('Peptgenderma9 Colágeno Premium sabor Neutro', 'Cod. 4465 - Lata c/300 g', 'Solúvel', 'Peptgenderma9 Colágeno'),
  ('Peptgenderma9 Colágeno Premium sabor Abacaxi e Hortelã', 'Cod. 7897 - Lata c/300 g', 'Solúvel', 'Peptgenderma9 Colágeno'),
  ('Peptgenderma9 Colágeno Premium sabor Frutas Vermelhas', 'Cod. 7896 - Lata c/300 g', 'Solúvel', 'Peptgenderma9 Colágeno'),
  ('Peptgen Care Colágeno VERISOL® e Ácido Hialurônico sabor Neutro', 'Cod. 5902 - Lata c/200 g', 'Solúvel', 'Peptgen Care'),
  ('Peptgen Care Colágeno VERISOL® sabor Laranja', 'Cod. 5900 - Lata c/200 g', 'Solúvel', 'Peptgen Care'),
  ('Peptgen Care Colágeno VERISOL® sabor Neutro', 'Cod. 5899 - Lata c/200 g', 'Solúvel', 'Peptgen Care'),
  ('Peptgen Care Colágeno VERISOL® sabor Piña Colada', 'Cod. 5901 - Lata c/200 g', 'Solúvel', 'Peptgen Care'),
  ('Artimag Mais Colágeno Tipo II sabor Neutro', 'Cod. 3599 - Lata c/150 g', 'Solúvel', 'Artimag Mais Colágeno'),
  ('Hyaluron+ - Colágeno 9 g e Ácido Hialurônico sabor Neutro', 'Cod. 4439 - Lata c/ 275 g', 'Solúvel', 'Hyaluron+'),
  ('Shake Mais com Chia BioForma sabor Banana com Canela', 'Cod. 6797 - Pote c/ 400 g', 'Solúvel', 'Shake Mais com'),
  ('Shake Mais com Chia BioForma sabor Morango', 'Cod. 6747 - Pote c/ 400 g', 'Solúvel', 'Shake Mais com'),
  ('Leveza 30 Shake com chia sabor Baunilha e 4 Leites', 'Cod. 7889 - Lata c/ 400 g', 'Solúvel', 'Leveza 30'),
  ('Choco Mais sabor Chocolate', 'Cod. 6743 - Lata c/ 150 g', 'Solúvel', 'Choco Mais sabor'),
  ('Mune + (Wellmune e Lactoferrina) - sabor Cranberry e Laranja', 'Cod. 12596 - Caixa c/ 10 sachês', 'Solúvel', 'Mune + (Wellmune e Lactoferrina)'),
  ('4 Fiber sabor Neutro', 'Cod. 16060 - Lata c/ 200 g', 'Solúvel', '4 Fiber'),
  ('Acetilcisteína com Vitamina C e Zinco sabor Laranja', 'Cod. 7719 - Caixa c/ 16 sachês', 'Solúvel', 'Acetilcisteína com'),
  ('BioFit sabor Abacaxi e Hortelã', 'Cod. 4009 - Lata c/ 200 g', 'Solúvel', 'BioFit sabor'),
  ('BioFit Hibisco sabor Frutas Vermelhas', 'Cod. 7912 - Lata c/ 200 g', 'Solúvel', 'BioFit Hibisco'),
  ('Creatina Monohidratada em pó', 'Cod. 7487 - Lata c/300 g', 'Solúvel', 'Creatina Monohidratada'),
  ('Creatina Monohidratada em pó', 'Cod. 6741 - Lata c/150 g', 'Solúvel', 'Creatina Monohidratada'),
  ('L-glutamina 100% - L-glutamina em pó', 'Cod. 14210 - Lata c/300 g', 'Solúvel', 'L-glutamina 100%'),
  ('Pré-treino Beta-alanina sabor Frutas Vermelhas', 'Cod. 7703 - Pote c/ 240 g', 'Solúvel', 'Pré-treino Beta-alanina'),
  ('Termogênic Mais Café sabor Chocolate - Pré-treino', 'Cod. 7203 - Lata c/ 220 g', 'Solúvel', 'Termogênic Mais Café sabor Chocolate'),
  ('Cloreto de Magnésio em pó', 'Cod. 6562 - Caixa c/ 20 sachês', 'Solúvel', 'Cloreto de'),
  ('Sal Amargo (Sulfato de Magnésio) em pó', 'Cod. 6866 - Pote c/ 30 g', 'Solúvel', 'Sal Amargo'),
  ('Creatina Gummies sabor Maçã Verde', 'Cod. 7678 - Pote c/ 60 und', 'Solúvel', 'Creatina Gummies'),
  ('Melatonina Gummies sabor Maracujá', 'Cod. 7671 - Pote c/ 30 und', 'Solúvel', 'Melatonina Gummies'),
  ('Vit.C+Zinco Gummies sabor Laranja', 'Cod. 7666 - Pote c/ 30 und.', 'Solúvel', 'Vit.C+Zinco Gummies'),
  ('3 Ômegas - Óleo de Peixe, Linhaça, Borragem e Vitamina E em cápsulas', 'Cod. 6705 - Pote c/ 60 cáps', 'Cápsula', '3 Ômegas'),
  ('5 Óleos - Óleo de linhaça, óleo de girassol, óleo de cártamo, óleo de borragem e óleo de chia em cápsulas', 'Cod. 7161 - Pote c/ 60 cáps', 'Cápsula', '5 Óleos'),
  ('CA - Óleo de Cártamo em cápsulas', 'Cod. 7463 - Pote c/ 60 cáps', 'Cápsula', 'CA'),
  ('Cart+Chia+Coco - Óleo de Chia, Cártamo e Coco em cápsulas', 'Cod. 7501 - Pote c/ 60 cáps', 'Cápsula', 'Cart+Chia+Coco'),
  ('Cártamo+Coco - Óleo de Cártamo e Óleo de Coco em cápsulas', 'Cod. 6355 - Pote c/ 60 cáps', 'Cápsula', 'Cártamo+Coco'),
  ('Chia+Coco - Óleo de Chia e Óleo de Coco em cápsulas', 'Cod. 6793 - Pote c/ 60 cáps', 'Cápsula', 'Chia+Coco'),
  ('Óleo de Alho Desodorizado em cápsulas', 'Cod. 4540 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Óleo de Abacate e Vitamina em cápsulas', 'Cod. 7177 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Óleo de Coco em cápsulas', 'Cod. 5284 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Óleo de Linhaça Dourada em cápsulas', 'Cod. 6263 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Óleo de Prímula e Borragem + L-triptofano em cápsulas', 'Cod. 7475 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Óleo de Prímula e Vitamina E em cápsulas', 'Cod. 6358 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Óleo de Semente de Abóbora em cápsulas', 'Cod. 6560 - Pote c/ 60 cáps', 'Cápsula', 'Óleo de'),
  ('Ômega-3 do Alaska - Óleo de Peixe e Vitamina E em cápsulas', 'Cod. 7523 - Pote c/ 60 cáps', 'Cápsula', 'Ômega-3 do Alaska'),
  ('Ômega-3 Mais 1000 - Óleo de Peixe e Vitamina E em cápsulas', 'Cod. 7230 - Pote c/ 90 cáps', 'Cápsula', 'Ômega-3 Mais 1000'),
  ('Vitamina D3 2000 UI em cápsulas', 'Cod. 5037 - Pote c/ 30 cáps', 'Cápsula', 'Vitamina D3'),
  ('Acetilcisteína - NAC em cápsulas', 'Cod. 8075 - Pote c/ 30 cáps', 'Cápsula', 'Acetilcisteína'),
  ('Ansiozen - Magnésio e L-triptofano em cápsulas', 'Cod. 4266 - Pote c/ 60 cáps', 'Cápsula', 'Ansiozen'),
  ('ArtiMag Mais Colágeno Tipo II e Magnésio em cápsulas', 'Cod. 7909 - Pote c/ 60 cáps', 'Cápsula', 'ArtiMag Mais Colágeno'),
  ('Bio Femme Mais cápsulas', 'Cod. 7740 - Pote c/ 30 cáps', 'Cápsula', 'Bio Femme'),
  ('BioBeard - Vitaminas e Minerais em cápsulas', 'Cod. 6746 - Pote c/ 30 cáps', 'Cápsula', 'BioBeard'),
  ('Bio Bella Cor cápsulas', 'Cod. 7685 - Pote c/ 30 cáps', 'Cápsula', 'Bio Bella'),
  ('BioBella - Vitaminas e Minerais em cápsulas', 'Cod. 3699 - Pote c/ 30 cáps', 'Cápsula', 'BioBella'),
  ('Caffeine Mais - Cafeína em cápsulas', 'Cod. 7511 - Pote c/ 60 cáps', 'Cápsula', 'Caffeine Mais'),
  ('Calmais Alga Lithothamniom cápsulas', 'Cod. 7592 - Pote c/ 60 cáps', 'Cápsula', 'Calmais Alga'),
  ('Calmais K2D3 com Magnésio e Cúrcuma em cápsulas', 'Cod. 7876 - Pote c/ 60 cáps', 'Cápsula', 'Calmais K2D3'),
  ('Cranberry em cápsulas', 'Cod. 7585 - Pote c/ 30 cáps', 'Cápsula', 'Cranberry em'),
  ('Creatina Monohidratada em cápsulas', 'Cod. 7229 - Pote c/ 60 cáps', 'Cápsula', 'Creatina Monohidratada'),
  ('Cúrcuma em cápsulas', 'Cod. 7509 - Pote c/ 30 cáps', 'Cápsula', 'Cúrcuma em'),
  ('Feno Grego - Trigonella foenum-graecum L. em cápsulas', 'Cod. 7446 - Pote c/ 30 cáps', 'Cápsula', 'Feno Grego'),
  ('Glucosamina MSM Colágeno Tipo II em cápsulas', 'Cod. 7507 - Pote c/ 60 cáps', 'Cápsula', 'Glucosamina MSM'),
  ('Green + Clorella - Ácido alfa-linolênico N3 obtido de Chlorella vulgaris', 'Cod. 7405 - Pote c/ 60 cáps', 'Cápsula', 'Green + Clorella'),
  ('Hyaluron + Ácido Hialurônico em cápsulas', 'Cod. 5551 - Pote c/ 30 cáps', 'Cápsula', 'Hyaluron +'),
  ('Licopeno + Trans-resveratrol + Vitamina E + Selênio em cápsulas', 'Cod. 7226 - Pote c/ 30 cáps', 'Cápsula', 'Licopeno +'),
  ('L&Z Luteína e Zeaxantina em cápsulas', 'Cod. 6731 - Pote c/ 30 cáps', 'Cápsula', 'L&Z Luteína'),
  ('Melatonina em cápsulas', 'Cod. 6404 - Pote c/ 30 cáps', 'Cápsula', 'Melatonina em'),
  ('Moro Mais - Café Verde, Laranja Moro e Cromo em cápsulas', 'Cod. 7525 - Pote c/ 60 cáps', 'Cápsula', 'Moro Mais'),
  ('Multivitaminas Mais - Multivitaminas e Multiminerais de A a Z', 'Cod. 7457 - Pote c/ 60 cáps', 'Cápsula', 'Multivitaminas Mais'),
  ('Peptgenderma Colágeno Hidrolisado Fragmentado', 'Cod. 6767 - Pote c/ 60 cáps', 'Cápsula', 'Peptgenderma Colágeno'),
  ('Pré-Treino Beta-Alanina', 'Cod. 7597 - Pote c/ 60 cáps', 'Cápsula', 'Pré-Treino Beta-Alanina'),
  ('Rejuvecel Coenzima Q10 + Semente de Uva em cápsulas', 'Cod. 7518 - Pote c/ 30 cáps', 'Cápsula', 'Rejuvecel Coenzima'),
  ('Spirulina Arthrospira platensis em cápsulas', 'Cod. 7139 - Pote c/ 60 cáps', 'Cápsula', 'Spirulina Arthrospira'),
  ('Suplemento de Cloreto de Magnésio em cápsulas', 'Cod. 7739 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Magnésio e Treonina em cápsulas', 'Cod. 7408 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Magnésio Malato em cápsulas', 'Cod. 7464 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento Mix 5 Magnésios em cápsulas', 'Cod. 7500 - Pote c/ 90 cáps', 'Cápsula', 'Suplemento Mix'),
  ('Suplemento de Picolinato de Cromo em cápsulas', 'Cod. 9835 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Selênio em cápsulas', 'Cod. 6754 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento Treonat Mais - Magnésio e L-treonina em cápsulas', 'Cod. 7197 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento Treonat Mais'),
  ('Suplemento de Vitamina B12 em cápsulas', 'Cod. 7187 - Pote c/ 30 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Vitamina C + Zinco em cápsulas', 'Cod. 7136 - Pote c/ 30 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Vitamina E em cápsulas', 'Cod. 7208 - Pote c/30 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Vitamina K2+D3 2000 UI em cápsulas', 'Cod. 6931 - Pote c/ 30 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Vitamina K2 (MK-7) em cápsulas', 'Cod. 4031 - Pote c/ 30 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Vitaminas do Complexo B em cápsulas', 'Cod. 7462 - Pote c/ 60 cáps', 'Cápsula', 'Suplemento de'),
  ('Suplemento de Zinco Quelato em cápsulas', 'Cod. 5978 - Pote c/ 30 cáps', 'Cápsula', 'Suplemento de'),
  ('Chá misto 30 Ervas, Flores e Frutas', 'Cod. 4187 - Caixa c/ 60 sachês', 'Chá', 'Chá misto'),
  ('Chá Leveza 30 - Dia e Noite', 'Cod. 4160 - Caixa c/ 60 sachês', 'Chá', 'Chá Leveza 30'),
  ('Leveza 30 Pink Lemonade', 'Cod. 7596 - Caixa c/ 15 sachês', 'Solúvel', 'Leveza 30'),
  ('Chá misto Bio Resfrin sabor Laranja', 'Cod. 5058 - Caixa c/ 30 sachês', 'Chá', 'Chá misto'),
  ('Chá Sublime Noite e Melatonina em cápsulas', 'Cod. 7854 - Caixa c/ 30 sachês e 36 cápsulas', 'Chá', 'Chá Sublime'),
  ('Chá misto Bom Dia Mais sabor Frutas Negras', 'Cod. 7438 - Caixa c/ 15 sachês', 'Chá', 'Chá misto'),
  ('Chá misto Boa Tarde Mais sabor Hortelã e Abacaxi', 'Cod. 7439 - Caixa c/ 15 sachês', 'Chá', 'Chá misto'),
  ('Chá misto Boa Noite Mais sabor Maracujá', 'Cod. 7437 - Caixa c/ 15 sachês', 'Chá', 'Chá misto'),
  ('Sublime Brisa sabor Maracujá', 'Cod. 12322 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Brisa'),
  ('Sublime Diva', 'Cod. 12324 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Diva'),
  ('Sublime Energia sabor Laranja e Guaraná', 'Cod. 12326 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Energia'),
  ('Sublime Essência', 'Cod. 12328 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Essência'),
  ('Sublime Harmonia', 'Cod. 12332 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Harmonia'),
  ('Sublime Inocência', 'Cod. 12334 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Inocência'),
  ('Sublime Inverno sabor Laranja e Mel', 'Cod. 12336 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Inverno'),
  ('Sublime Leveza sabor Abacaxi', 'Cod. 12338 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Leveza'),
  ('Sublime Liberdade', 'Cod. 12340 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Liberdade'),
  ('Sublime Noite', 'Cod. 12342 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Noite'),
  ('Sublime Paixão sabor Cereja e Framboesa', 'Cod. 12344 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Paixão'),
  ('Sublime Ternura', 'Cod. 12348 - Caixa c/ 10 sachês', 'Solúvel', 'Sublime Ternura'),
  ('Anis-estrelado', 'Cod. 2188 - Caixa c/ 10 sachês', 'Solúvel', 'Anis-estrelado'),
  ('Camomila e Laranja sabor Mel', 'Cod. 4282 - Caixa c/ 10 sachês', 'Solúvel', 'Camomila e'),
  ('Mate e Capim-cidreira com Alecrim sabor Limão', 'Cod. 5288 - Caixa c/ 10 sachês', 'Solúvel', 'Mate e'),
  ('Funcho', 'Cod. 7413 - Caixa c/ 10 sachês', 'Solúvel', 'Funcho'),
  ('Hibisco', 'Cod. 1359 - Caixa c/ 10 sachês', 'Solúvel', 'Hibisco'),
  ('Frutas Vermelhas sabor artificial de Morango', 'Cod. 4280 - Caixa c/ 10 sachês', 'Solúvel', 'Frutas Vermelhas'),
  ('Silvestre sabor artificial de Cereja e Framboesa', 'Cod. 4283 - Caixa c/ 10 sachês', 'Solúvel', 'Silvestre sabor');
