alter table public."Clinic+ - Catálogo Front B2B"
  add column if not exists price numeric(12,2) not null default 0;

update public."Clinic+ - Catálogo Front B2B" set price = 126.70 where name = 'Whey Mais Ella Isolado + Colágeno sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 129.25 where name = 'Whey Mais Ella Isolado + Colágeno sabor Banana Flambada';
update public."Clinic+ - Catálogo Front B2B" set price = 130.67 where name = 'Whey Mais Ella Isolado + Colágeno sabor Mousse de Limão';
update public."Clinic+ - Catálogo Front B2B" set price = 86.26 where name = 'Whey Mais Pleno Isolado sabor Baunilha';
update public."Clinic+ - Catálogo Front B2B" set price = 339.61 where name = 'Whey Mais ISO sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 159.70 where name = 'Whey Mais 100% Concentrate sabor Morango';
update public."Clinic+ - Catálogo Front B2B" set price = 193.69 where name = 'Whey Mais 100% Concentrate sabor Chocolate Belga';
update public."Clinic+ - Catálogo Front B2B" set price = 160.43 where name = 'Whey Mais 100% Concentrate sabor Baunilha e Banana Caramelizada';
update public."Clinic+ - Catálogo Front B2B" set price = 106.43 where name = 'Whey Mais Concentrado sabor Chocolate';
update public."Clinic+ - Catálogo Front B2B" set price = 105.93 where name = 'Whey Mais Concentrado sabor Morango';
update public."Clinic+ - Catálogo Front B2B" set price = 103.49 where name = 'Whey Mais Concentrado sabor Baunilha e Quatro Leites';
update public."Clinic+ - Catálogo Front B2B" set price = 149.99 where name = 'Protein Mais Colágeno Hidrolisado BODYBALANCE® sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgenderma9 Colágeno Premium sabor Laranja com Gengibre';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgenderma9 Colágeno Premium sabor Limão Siciliano';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgenderma9 Colágeno Premium sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgenderma9 Colágeno Premium sabor Abacaxi e Hortelã';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgenderma9 Colágeno Premium sabor Frutas Vermelhas';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgen Care Colágeno VERISOL® e Ácido Hialurônico sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgen Care Colágeno VERISOL® sabor Laranja';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgen Care Colágeno VERISOL® sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 79.99 where name = 'Peptgen Care Colágeno VERISOL® sabor Piña Colada';
update public."Clinic+ - Catálogo Front B2B" set price = 47.99 where name = 'Artimag Mais Colágeno Tipo II sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 59.99 where name = 'Hyaluron+ - Colágeno 9 g e Ácido Hialurônico sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Shake Mais com Chia BioForma sabor Banana com Canela';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Shake Mais com Chia BioForma sabor Morango';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Leveza 30 Shake com chia sabor Baunilha e 4 Leites';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Choco Mais sabor Chocolate';
update public."Clinic+ - Catálogo Front B2B" set price = 143.99 where name = 'Mune + (Wellmune e Lactoferrina) - sabor Cranberry e Laranja';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = '4 Fiber sabor Neutro';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Acetilcisteína com Vitamina C e Zinco sabor Laranja';
update public."Clinic+ - Catálogo Front B2B" set price = 29.99 where name = 'BioFit sabor Abacaxi e Hortelã';
update public."Clinic+ - Catálogo Front B2B" set price = 29.99 where name = 'BioFit Hibisco sabor Frutas Vermelhas';
update public."Clinic+ - Catálogo Front B2B" set price = 27.99 where name = 'Creatina Monohidratada em pó';
update public."Clinic+ - Catálogo Front B2B" set price = 69.99 where name = 'L-glutamina 100% - L-glutamina em pó';
update public."Clinic+ - Catálogo Front B2B" set price = 0.00 where name = 'Pré-treino Beta-alanina sabor Frutas Vermelhas';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Termogênic Mais Café sabor Chocolate - Pré-treino';
update public."Clinic+ - Catálogo Front B2B" set price = 69.90 where name = 'Cloreto de Magnésio em pó';
update public."Clinic+ - Catálogo Front B2B" set price = 13.99 where name = 'Sal Amargo (Sulfato de Magnésio) em pó';
update public."Clinic+ - Catálogo Front B2B" set price = 79.00 where name = 'Creatina Gummies sabor Maçã Verde';
update public."Clinic+ - Catálogo Front B2B" set price = 23.00 where name = 'Melatonina Gummies sabor Maracujá';
update public."Clinic+ - Catálogo Front B2B" set price = 29.00 where name = 'Vit.C+Zinco Gummies sabor Laranja';
update public."Clinic+ - Catálogo Front B2B" set price = 32.99 where name = '3 Ômegas - Óleo de Peixe, Linhaça, Borragem e Vitamina E em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = '5 ?leos - ?leo de linha?a, ?leo de girassol, ?leo de c?rtamo, ?leo de borragem e ?leo de chia em c?psulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'CA - Óleo de Cártamo em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Cart+Chia+Coco - Óleo de Chia, Cártamo e Coco em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 0.00 where name = 'Cártamo+Coco - Óleo de Cártamo e Óleo de Coco em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Chia+Coco - Óleo de Chia e Óleo de Coco em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 17.99 where name = 'Óleo de Alho Desodorizado em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Óleo de Abacate e Vitamina em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Óleo de Coco em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Óleo de Linhaça Dourada em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Óleo de Prímula e Borragem + L-triptofano em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 25.99 where name = 'Óleo de Prímula e Vitamina E em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 32.99 where name = 'Óleo de Semente de Abóbora em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 69.99 where name = 'Ômega-3 do Alaska - Óleo de Peixe e Vitamina E em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 55.99 where name = 'Ômega-3 Mais 1000 - Óleo de Peixe e Vitamina E em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 17.99 where name = 'Vitamina D3 2000 UI em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 29.99 where name = 'Acetilcisteína - NAC em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 25.99 where name = 'Ansiozen - Magnésio e L-triptofano em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'ArtiMag Mais Colágeno Tipo II e Magnésio em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 22.99 where name = 'Bio Femme Mais cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 22.99 where name = 'BioBeard - Vitaminas e Minerais em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 32.99 where name = 'Bio Bella Cor cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 22.99 where name = 'BioBella - Vitaminas e Minerais em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 19.99 where name = 'Caffeine Mais - Cafeína em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 35.99 where name = 'Calmais Alga Lithothamniom cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 35.99 where name = 'Calmais K2D3 com Magnésio e Cúrcuma em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 35.99 where name = 'Cranberry em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Creatina Monohidratada em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 23.99 where name = 'Cúrcuma em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 69.99 where name = 'Feno Grego - Trigonella foenum-graecum L. em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 59.99 where name = 'Glucosamina MSM Colágeno Tipo II em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 35.99 where name = 'Green + Clorella - Ácido alfa-linolênico N3 obtido de Chlorella vulgaris';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Hyaluron + Ácido Hialurônico em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 44.99 where name = 'Licopeno + Trans-resveratrol + Vitamina E + Selênio em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 35.99 where name = 'L&Z Luteína e Zeaxantina em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 19.99 where name = 'Melatonina em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 69.99 where name = 'Moro Mais - Café Verde, Laranja Moro e Cromo em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 27.99 where name = 'Multivitaminas Mais - Multivitaminas e Multiminerais de A a Z';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Peptgenderma Colágeno Hidrolisado Fragmentado';
update public."Clinic+ - Catálogo Front B2B" set price = 23.99 where name = 'Pré-Treino Beta-Alanina';
update public."Clinic+ - Catálogo Front B2B" set price = 39.99 where name = 'Rejuvecel Coenzima Q10 + Semente de Uva em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 31.99 where name = 'Spirulina Arthrospira platensis em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Suplemento de Cloreto de Magnésio em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 29.99 where name = 'Suplemento de Magnésio e Treonina em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Suplemento de Magnésio Malato em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 29.99 where name = 'Suplemento Mix 5 Magnésios em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 23.99 where name = 'Suplemento de Picolinato de Cromo em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 19.99 where name = 'Suplemento de Selênio em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 29.99 where name = 'Suplemento Treonat Mais - Magnésio e L-treonina em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Suplemento de Vitamina B12 em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 20.99 where name = 'Suplemento de Vitamina C + Zinco em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Suplemento de Vitamina E em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Suplemento de Vitamina K2+D3 2000 UI em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 24.99 where name = 'Suplemento de Vitamina K2 (MK-7) em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 26.99 where name = 'Suplemento de Vitaminas do Complexo B em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 17.99 where name = 'Suplemento de Zinco Quelato em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 0.00 where name = 'Chá misto 30 Ervas, Flores e Frutas';
update public."Clinic+ - Catálogo Front B2B" set price = 37.99 where name = 'Chá Leveza 30 - Dia e Noite';
update public."Clinic+ - Catálogo Front B2B" set price = 16.99 where name = 'Leveza 30 Pink Lemonade';
update public."Clinic+ - Catálogo Front B2B" set price = 24.90 where name = 'Chá misto Bio Resfrin sabor Laranja';
update public."Clinic+ - Catálogo Front B2B" set price = 4.07 where name = 'Chá Sublime Noite e Melatonina em cápsulas';
update public."Clinic+ - Catálogo Front B2B" set price = 9.90 where name = 'Chá misto Bom Dia Mais sabor Frutas Negras';
update public."Clinic+ - Catálogo Front B2B" set price = 9.90 where name = 'Chá misto Boa Tarde Mais sabor Hortelã e Abacaxi';
update public."Clinic+ - Catálogo Front B2B" set price = 9.90 where name = 'Chá misto Boa Noite Mais sabor Maracujá';
update public."Clinic+ - Catálogo Front B2B" set price = 4.33 where name = 'Sublime Brisa sabor Maracujá';
update public."Clinic+ - Catálogo Front B2B" set price = 3.83 where name = 'Sublime Diva';
update public."Clinic+ - Catálogo Front B2B" set price = 4.83 where name = 'Sublime Energia sabor Laranja e Guaraná';
update public."Clinic+ - Catálogo Front B2B" set price = 3.74 where name = 'Sublime Essência';
update public."Clinic+ - Catálogo Front B2B" set price = 3.98 where name = 'Sublime Harmonia';
update public."Clinic+ - Catálogo Front B2B" set price = 3.67 where name = 'Sublime Inocência';
update public."Clinic+ - Catálogo Front B2B" set price = 5.35 where name = 'Sublime Inverno sabor Laranja e Mel';
update public."Clinic+ - Catálogo Front B2B" set price = 4.31 where name = 'Sublime Leveza sabor Abacaxi';
update public."Clinic+ - Catálogo Front B2B" set price = 4.15 where name = 'Sublime Liberdade';
update public."Clinic+ - Catálogo Front B2B" set price = 4.07 where name = 'Sublime Noite';
update public."Clinic+ - Catálogo Front B2B" set price = 5.63 where name = 'Sublime Paixão sabor Cereja e Framboesa';
update public."Clinic+ - Catálogo Front B2B" set price = 4.15 where name = 'Sublime Ternura';
update public."Clinic+ - Catálogo Front B2B" set price = 4.84 where name = 'Anis-estrelado';
update public."Clinic+ - Catálogo Front B2B" set price = 3.58 where name = 'Camomila e Laranja sabor Mel';
update public."Clinic+ - Catálogo Front B2B" set price = 4.17 where name = 'Mate e Capim-cidreira com Alecrim sabor Limão';
update public."Clinic+ - Catálogo Front B2B" set price = 3.31 where name = 'Funcho';
update public."Clinic+ - Catálogo Front B2B" set price = 4.37 where name = 'Hibisco';
update public."Clinic+ - Catálogo Front B2B" set price = 6.01 where name = 'Frutas Vermelhas sabor artificial de Morango';
update public."Clinic+ - Catálogo Front B2B" set price = 5.57 where name = 'Silvestre sabor artificial de Cereja e Framboesa';
